server:
  port: 1001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/timeAlreadyLocked/config-center.git
  application:
    name: config-server
  profiles:
    active: dev